services:
  postgres:
    image: postgres:latest
    container_name: payment_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
