version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - survey-network
    ports:
      - '${POSTGRES_PORT}:5432'

  secretdb:
    image: 'postgres:latest'
    container_name: secretdb
    environment:
      POSTGRES_DB: ${POSTGRES_SecretDB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - survey-network
    ports:
      - '${POSTGRES_SecretDB_PORT}:5432'

  online-survey:
    build: .
    container_name: online-survey
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - TZ=Asia/Tehran
      - CONFIG_PATH=/app/config.json
    networks:
      - survey-network
    restart: unless-stopped
    depends_on:
      - postgres
      - secretdb
    volumes:
      - ${CONFIG_PATH}:/app/config.json

networks:
  survey-network:
    driver: bridge
