// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.1
// source: travel.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookTravelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TravelId      string                 `protobuf:"bytes,1,opt,name=travel_id,json=travelId,proto3" json:"travel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTravelRequest) Reset() {
	*x = BookTravelRequest{}
	mi := &file_travel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTravelRequest) ProtoMessage() {}

func (x *BookTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTravelRequest.ProtoReflect.Descriptor instead.
func (*BookTravelRequest) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{0}
}

func (x *BookTravelRequest) GetTravelId() string {
	if x != nil {
		return x.TravelId
	}
	return ""
}

type BookTravelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTravelResponse) Reset() {
	*x = BookTravelResponse{}
	mi := &file_travel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTravelResponse) ProtoMessage() {}

func (x *BookTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTravelResponse.ProtoReflect.Descriptor instead.
func (*BookTravelResponse) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{1}
}

func (x *BookTravelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BookTravelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TravelId      string                 `protobuf:"bytes,1,opt,name=travel_id,json=travelId,proto3" json:"travel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_travel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{2}
}

func (x *CancelBookingRequest) GetTravelId() string {
	if x != nil {
		return x.TravelId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_travel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{3}
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelTravelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TravelId      string                 `protobuf:"bytes,1,opt,name=travel_id,json=travelId,proto3" json:"travel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTravelRequest) Reset() {
	*x = CancelTravelRequest{}
	mi := &file_travel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTravelRequest) ProtoMessage() {}

func (x *CancelTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTravelRequest.ProtoReflect.Descriptor instead.
func (*CancelTravelRequest) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTravelRequest) GetTravelId() string {
	if x != nil {
		return x.TravelId
	}
	return ""
}

type CancelTravelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTravelResponse) Reset() {
	*x = CancelTravelResponse{}
	mi := &file_travel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTravelResponse) ProtoMessage() {}

func (x *CancelTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTravelResponse.ProtoReflect.Descriptor instead.
func (*CancelTravelResponse) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTravelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelTravelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ApproveTravelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TravelId      string                 `protobuf:"bytes,1,opt,name=travel_id,json=travelId,proto3" json:"travel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTravelRequest) Reset() {
	*x = ApproveTravelRequest{}
	mi := &file_travel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTravelRequest) ProtoMessage() {}

func (x *ApproveTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTravelRequest.ProtoReflect.Descriptor instead.
func (*ApproveTravelRequest) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveTravelRequest) GetTravelId() string {
	if x != nil {
		return x.TravelId
	}
	return ""
}

type ApproveTravelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTravelResponse) Reset() {
	*x = ApproveTravelResponse{}
	mi := &file_travel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTravelResponse) ProtoMessage() {}

func (x *ApproveTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTravelResponse.ProtoReflect.Descriptor instead.
func (*ApproveTravelResponse) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveTravelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApproveTravelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FinishTravelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TravelId      string                 `protobuf:"bytes,1,opt,name=travel_id,json=travelId,proto3" json:"travel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTravelRequest) Reset() {
	*x = FinishTravelRequest{}
	mi := &file_travel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTravelRequest) ProtoMessage() {}

func (x *FinishTravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTravelRequest.ProtoReflect.Descriptor instead.
func (*FinishTravelRequest) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{8}
}

func (x *FinishTravelRequest) GetTravelId() string {
	if x != nil {
		return x.TravelId
	}
	return ""
}

type FinishTravelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTravelResponse) Reset() {
	*x = FinishTravelResponse{}
	mi := &file_travel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTravelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTravelResponse) ProtoMessage() {}

func (x *FinishTravelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_travel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTravelResponse.ProtoReflect.Descriptor instead.
func (*FinishTravelResponse) Descriptor() ([]byte, []int) {
	return file_travel_proto_rawDescGZIP(), []int{9}
}

func (x *FinishTravelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FinishTravelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_travel_proto protoreflect.FileDescriptor

var file_travel_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30,
	0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x14, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x22,
	0x4b, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x32, 0x0a, 0x13,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0x4a, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x33, 0x0a, 0x14,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x49,
	0x64, 0x22, 0x4b, 0x0a, 0x15, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x32,
	0x0a, 0x13, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x61, 0x76, 0x65, 0x6c,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xc6,
	0x02, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x72,
	0x61, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x72, 0x61, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x15,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a,
	0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x2e,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0d, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x54, 0x72, 0x61, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x46, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x2e, 0x46, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x72, 0x61, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x51, 0x42, 0x43, 0x38, 0x2d, 0x47, 0x4f, 0x2d, 0x47, 0x52,
	0x4f, 0x55, 0x50, 0x2f, 0x47, 0x68, 0x6f, 0x6c, 0x69, 0x42, 0x61, 0x62, 0x61, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_travel_proto_rawDescOnce sync.Once
	file_travel_proto_rawDescData = file_travel_proto_rawDesc
)

func file_travel_proto_rawDescGZIP() []byte {
	file_travel_proto_rawDescOnce.Do(func() {
		file_travel_proto_rawDescData = protoimpl.X.CompressGZIP(file_travel_proto_rawDescData)
	})
	return file_travel_proto_rawDescData
}

var file_travel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_travel_proto_goTypes = []any{
	(*BookTravelRequest)(nil),     // 0: BookTravelRequest
	(*BookTravelResponse)(nil),    // 1: BookTravelResponse
	(*CancelBookingRequest)(nil),  // 2: CancelBookingRequest
	(*CancelBookingResponse)(nil), // 3: CancelBookingResponse
	(*CancelTravelRequest)(nil),   // 4: CancelTravelRequest
	(*CancelTravelResponse)(nil),  // 5: CancelTravelResponse
	(*ApproveTravelRequest)(nil),  // 6: ApproveTravelRequest
	(*ApproveTravelResponse)(nil), // 7: ApproveTravelResponse
	(*FinishTravelRequest)(nil),   // 8: FinishTravelRequest
	(*FinishTravelResponse)(nil),  // 9: FinishTravelResponse
}
var file_travel_proto_depIdxs = []int32{
	0, // 0: TravelAgencyService.BookTravel:input_type -> BookTravelRequest
	2, // 1: TravelAgencyService.CancelBooking:input_type -> CancelBookingRequest
	4, // 2: TravelAgencyService.CancelTravel:input_type -> CancelTravelRequest
	6, // 3: TravelAgencyService.ApproveTravel:input_type -> ApproveTravelRequest
	8, // 4: TravelAgencyService.FinishTravel:input_type -> FinishTravelRequest
	1, // 5: TravelAgencyService.BookTravel:output_type -> BookTravelResponse
	3, // 6: TravelAgencyService.CancelBooking:output_type -> CancelBookingResponse
	5, // 7: TravelAgencyService.CancelTravel:output_type -> CancelTravelResponse
	7, // 8: TravelAgencyService.ApproveTravel:output_type -> ApproveTravelResponse
	9, // 9: TravelAgencyService.FinishTravel:output_type -> FinishTravelResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_travel_proto_init() }
func file_travel_proto_init() {
	if File_travel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_travel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_travel_proto_goTypes,
		DependencyIndexes: file_travel_proto_depIdxs,
		MessageInfos:      file_travel_proto_msgTypes,
	}.Build()
	File_travel_proto = out.File
	file_travel_proto_rawDesc = nil
	file_travel_proto_goTypes = nil
	file_travel_proto_depIdxs = nil
}
